Fix "argument type/size mismatch" error.
When incorrectly implementing an x86_64 instruction the compiler error
message currently makes wrong suggestions about what the correct input
should be. For example,

```
dynasm!(self.asm; shl Rq(Rq::RDX.code()), Rq::RAX.code()))
```

gives the following error:

```
error: 'shl': argument type/size mismatch, expected one of the following forms:
>>> shl reg/mem8, dl
>>> shl reg/mem8, imm8
>>> shl reg/mem64, dl
>>> shl reg/mem16, dl
...
```

However, `shl` and `shr` require the shift amount to be in the `CL`
register. This commit fixes the ordering of the register array used by
the error formatting to make it match the ordering in the AMD64 manual.