Fix `cargo doc` error.
```
$ cargo doc
error: document output filename collision
The bin `aarch64` in package `hello-world v0.1.0 (/home/vext01/source/dynasm-rs/doc/examples/hello-world)` has the same name as the bin `aarch64` in package `bf-jit v0.1.0 (/home/vext01/source/dynasm-rs/doc/examples/bf-jit)`.
Only one may be documented at once since they output to the same path.
Consider documenting only one, renaming one, or marking one with `doc = false` in Cargo.toml.
```